[package]
name = "clock_sync"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
tokio = { version = "1.45.1", features = ["full"] }
tokio-stream = "0.1.17"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[lib]
name = "clock_sync_lib"
path = "src/lib.rs"
